repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
    stages: [commit]
  - id: mixed-line-ending
    args: ["-f", "lf"]
    exclude: \.bat$
    stages: [commit]
  - id: check-added-large-files
    stages: [commit]
  - id: check-case-conflict
    stages: [commit]
  - id: check-merge-conflict
    stages: [commit]
  - id: forbid-new-submodules
    stages: [commit]
  - id: check-executables-have-shebangs
    stages: [commit]
  - id: check-symlinks
    stages: [commit]
  - id: end-of-file-fixer
    stages: [commit]
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.12.0
  hooks:
  - id: gitlint
    stages: [commit-msg]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 1.11.2
  hooks:
  - id: shellcheck
    stages: [commit]
    args: ["-e", "SC2211"]
- repo: https://github.com/golangci/golangci-lint
  rev: v1.37.0
  hooks:
  - id: golangci-lint
    args: ["--fix", "-c", ".golangci.yml"]
    stages: [commit]
