language: go
install:
    - go get github.com/alecthomas/gometalinter
    - go get github.com/makkes/assert
script:
    - gometalinter --install
    - gometalinter -D errcheck ./...
    - go test ./...
